version: 1
disable_existing_loggers: false
root:
  handlers:
    - console
formatters:
  default:
    format: "%(asctime)s | %(levelname)-8s | %(name)-30s: %(message)s"
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
